// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/db.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Read data from a table. Lookup can be by ID or via querying any field in the record.
type ReadRequest struct {
	// Optional table name. Defaults to 'default'
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Read by id, Equivalent to 'id == "your-id"'
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Examples: 'age >= 18', 'age >= 18 and verified == true'
	// Comparison operators: '==', '!=', '<', '>', '<=', '>='
	// Logical operator: 'and'
	// Dot access is supported, eg: 'user.age == 11'
	// Accessing list elements is not supported yet.
	Query  string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Offset int32  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Maximum number of records to return. Default limit is 25.
	// Maximum limit is 1000. anything higher will return an error.
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// field name to order by
	OrderBy string `protobuf:"bytes,6,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	// 'asc' (default), 'desc'
	Order                string   `protobuf:"bytes,7,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{0}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ReadRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *ReadRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type ReadResponse struct {
	// JSON encoded records
	Records              []*_struct.Struct `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{1}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetRecords() []*_struct.Struct {
	if m != nil {
		return m.Records
	}
	return nil
}

// Create a record in the database. Optionally include an "id" field
// otherwise it's set automatically.
type CreateRequest struct {
	// Optional table name. Defaults to 'default'
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// JSON encoded record or records (can be array or object)
	Record *_struct.Struct `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	// ooptional record id to use.
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CreateRequest) GetRecord() *_struct.Struct {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateResponse struct {
	// The id of the record (either specified or automatically created)
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Update a record in the database. Include an "id" in the record to update
type UpdateRequest struct {
	// optional table name. Defaults to 'default'
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// The id of the record. If not specified it is inferred from the 'id' field of the record
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// record, JSON object.
	Record               *_struct.Struct `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetRecord() *_struct.Struct {
	if m != nil {
		return m.Record
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{5}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

// Delete a record in the database by id.
type DeleteRequest struct {
	// optional table name. Default to 'default'
	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// id of the record
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// Truncate the records in a table
type TruncateRequest struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateRequest) Reset()         { *m = TruncateRequest{} }
func (m *TruncateRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateRequest) ProtoMessage()    {}
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{8}
}

func (m *TruncateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateRequest.Unmarshal(m, b)
}
func (m *TruncateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateRequest.Marshal(b, m, deterministic)
}
func (m *TruncateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateRequest.Merge(m, src)
}
func (m *TruncateRequest) XXX_Size() int {
	return xxx_messageInfo_TruncateRequest.Size(m)
}
func (m *TruncateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateRequest proto.InternalMessageInfo

func (m *TruncateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type TruncateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateResponse) Reset()         { *m = TruncateResponse{} }
func (m *TruncateResponse) String() string { return proto.CompactTextString(m) }
func (*TruncateResponse) ProtoMessage()    {}
func (*TruncateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{9}
}

func (m *TruncateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateResponse.Unmarshal(m, b)
}
func (m *TruncateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateResponse.Marshal(b, m, deterministic)
}
func (m *TruncateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateResponse.Merge(m, src)
}
func (m *TruncateResponse) XXX_Size() int {
	return xxx_messageInfo_TruncateResponse.Size(m)
}
func (m *TruncateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateResponse proto.InternalMessageInfo

// Count records in a table
type CountRequest struct {
	// specify table name
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{10}
}

func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (m *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(m, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

func (m *CountRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type CountResponse struct {
	// The number of records in the table
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{11}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Rename a table
type RenameTableRequest struct {
	// current table name
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// new table name
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameTableRequest) Reset()         { *m = RenameTableRequest{} }
func (m *RenameTableRequest) String() string { return proto.CompactTextString(m) }
func (*RenameTableRequest) ProtoMessage()    {}
func (*RenameTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{12}
}

func (m *RenameTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameTableRequest.Unmarshal(m, b)
}
func (m *RenameTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameTableRequest.Marshal(b, m, deterministic)
}
func (m *RenameTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameTableRequest.Merge(m, src)
}
func (m *RenameTableRequest) XXX_Size() int {
	return xxx_messageInfo_RenameTableRequest.Size(m)
}
func (m *RenameTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameTableRequest proto.InternalMessageInfo

func (m *RenameTableRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RenameTableRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type RenameTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameTableResponse) Reset()         { *m = RenameTableResponse{} }
func (m *RenameTableResponse) String() string { return proto.CompactTextString(m) }
func (*RenameTableResponse) ProtoMessage()    {}
func (*RenameTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{13}
}

func (m *RenameTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameTableResponse.Unmarshal(m, b)
}
func (m *RenameTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameTableResponse.Marshal(b, m, deterministic)
}
func (m *RenameTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameTableResponse.Merge(m, src)
}
func (m *RenameTableResponse) XXX_Size() int {
	return xxx_messageInfo_RenameTableResponse.Size(m)
}
func (m *RenameTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameTableResponse proto.InternalMessageInfo

// List tables in the DB
type ListTablesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTablesRequest) Reset()         { *m = ListTablesRequest{} }
func (m *ListTablesRequest) String() string { return proto.CompactTextString(m) }
func (*ListTablesRequest) ProtoMessage()    {}
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{14}
}

func (m *ListTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTablesRequest.Unmarshal(m, b)
}
func (m *ListTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTablesRequest.Marshal(b, m, deterministic)
}
func (m *ListTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTablesRequest.Merge(m, src)
}
func (m *ListTablesRequest) XXX_Size() int {
	return xxx_messageInfo_ListTablesRequest.Size(m)
}
func (m *ListTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTablesRequest proto.InternalMessageInfo

type ListTablesResponse struct {
	// list of tables
	Tables               []string `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTablesResponse) Reset()         { *m = ListTablesResponse{} }
func (m *ListTablesResponse) String() string { return proto.CompactTextString(m) }
func (*ListTablesResponse) ProtoMessage()    {}
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{15}
}

func (m *ListTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTablesResponse.Unmarshal(m, b)
}
func (m *ListTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTablesResponse.Marshal(b, m, deterministic)
}
func (m *ListTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTablesResponse.Merge(m, src)
}
func (m *ListTablesResponse) XXX_Size() int {
	return xxx_messageInfo_ListTablesResponse.Size(m)
}
func (m *ListTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTablesResponse proto.InternalMessageInfo

func (m *ListTablesResponse) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

// Drop a table in the DB
type DropTableRequest struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropTableRequest) Reset()         { *m = DropTableRequest{} }
func (m *DropTableRequest) String() string { return proto.CompactTextString(m) }
func (*DropTableRequest) ProtoMessage()    {}
func (*DropTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{16}
}

func (m *DropTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTableRequest.Unmarshal(m, b)
}
func (m *DropTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTableRequest.Marshal(b, m, deterministic)
}
func (m *DropTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTableRequest.Merge(m, src)
}
func (m *DropTableRequest) XXX_Size() int {
	return xxx_messageInfo_DropTableRequest.Size(m)
}
func (m *DropTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropTableRequest proto.InternalMessageInfo

func (m *DropTableRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type DropTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropTableResponse) Reset()         { *m = DropTableResponse{} }
func (m *DropTableResponse) String() string { return proto.CompactTextString(m) }
func (*DropTableResponse) ProtoMessage()    {}
func (*DropTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_903744a76531f483, []int{17}
}

func (m *DropTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTableResponse.Unmarshal(m, b)
}
func (m *DropTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTableResponse.Marshal(b, m, deterministic)
}
func (m *DropTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTableResponse.Merge(m, src)
}
func (m *DropTableResponse) XXX_Size() int {
	return xxx_messageInfo_DropTableResponse.Size(m)
}
func (m *DropTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropTableResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReadRequest)(nil), "db.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "db.ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "db.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "db.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "db.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "db.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "db.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "db.DeleteResponse")
	proto.RegisterType((*TruncateRequest)(nil), "db.TruncateRequest")
	proto.RegisterType((*TruncateResponse)(nil), "db.TruncateResponse")
	proto.RegisterType((*CountRequest)(nil), "db.CountRequest")
	proto.RegisterType((*CountResponse)(nil), "db.CountResponse")
	proto.RegisterType((*RenameTableRequest)(nil), "db.RenameTableRequest")
	proto.RegisterType((*RenameTableResponse)(nil), "db.RenameTableResponse")
	proto.RegisterType((*ListTablesRequest)(nil), "db.ListTablesRequest")
	proto.RegisterType((*ListTablesResponse)(nil), "db.ListTablesResponse")
	proto.RegisterType((*DropTableRequest)(nil), "db.DropTableRequest")
	proto.RegisterType((*DropTableResponse)(nil), "db.DropTableResponse")
}

func init() {
	proto.RegisterFile("proto/db.proto", fileDescriptor_903744a76531f483)
}

var fileDescriptor_903744a76531f483 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0xac, 0x93, 0xda, 0x25, 0xaf, 0x49, 0x9a, 0x6c, 0x3e, 0x6a, 0x59, 0x1c, 0xa2, 0x15, 0x88,
	0x48, 0x20, 0x47, 0x29, 0x42, 0x20, 0x10, 0x12, 0xb4, 0x39, 0x72, 0x32, 0xe5, 0xc2, 0x2d, 0x8e,
	0xd7, 0x55, 0xa4, 0x24, 0x9b, 0xae, 0xd7, 0x87, 0xfe, 0x22, 0xfe, 0x1e, 0x3f, 0x01, 0xed, 0xbe,
	0x5d, 0xc7, 0x76, 0x51, 0x0a, 0x37, 0xbf, 0xc9, 0xcc, 0x78, 0xde, 0xee, 0xc4, 0xd0, 0xdd, 0x0b,
	0x2e, 0xf9, 0x2c, 0x89, 0x43, 0xfd, 0x40, 0x1a, 0x49, 0x1c, 0x3c, 0xbf, 0xe3, 0xfc, 0x6e, 0xc3,
	0x66, 0x1a, 0x89, 0xf3, 0x74, 0x96, 0x49, 0x91, 0xaf, 0x24, 0x32, 0xe8, 0x2f, 0x07, 0xce, 0x23,
	0xb6, 0x4c, 0x22, 0x76, 0x9f, 0xb3, 0x4c, 0x92, 0x21, 0xb8, 0x72, 0x19, 0x6f, 0x98, 0xef, 0x4c,
	0x9c, 0x69, 0x2b, 0xc2, 0x81, 0x74, 0xa1, 0xb1, 0x4e, 0xfc, 0x86, 0x86, 0x1a, 0xeb, 0x44, 0xb1,
	0xee, 0x73, 0x26, 0x1e, 0xfc, 0x26, 0xb2, 0xf4, 0x40, 0xc6, 0xe0, 0xf1, 0x34, 0xcd, 0x98, 0xf4,
	0x4f, 0x27, 0xce, 0xd4, 0x8d, 0xcc, 0xa4, 0xd8, 0x9b, 0xf5, 0x76, 0x2d, 0x7d, 0x57, 0xc3, 0x38,
	0x10, 0x1f, 0xce, 0xb8, 0x48, 0x98, 0xb8, 0x7e, 0xf0, 0x3d, 0xed, 0x62, 0x47, 0xc5, 0xd7, 0x8f,
	0xfe, 0x19, 0xba, 0xeb, 0x81, 0x7e, 0x85, 0x36, 0x06, 0xcd, 0xf6, 0x7c, 0x97, 0x31, 0x32, 0x87,
	0x33, 0xc1, 0x56, 0x5c, 0x24, 0x99, 0xef, 0x4c, 0x9a, 0xd3, 0xf3, 0xab, 0xcb, 0x10, 0x37, 0x0d,
	0xed, 0xa6, 0xe1, 0x77, 0xbd, 0x69, 0x64, 0x79, 0x34, 0x85, 0xce, 0x8d, 0x60, 0x4b, 0xc9, 0x8e,
	0x6f, 0x3b, 0x03, 0x0f, 0x15, 0x7a, 0xe3, 0x23, 0xc6, 0x86, 0x66, 0x8e, 0xa7, 0x69, 0x8f, 0x87,
	0x4e, 0xa0, 0x6b, 0xdf, 0x63, 0xc2, 0x22, 0xc3, 0x29, 0x18, 0x29, 0x74, 0x7e, 0xec, 0x93, 0x27,
	0x93, 0xd4, 0xcf, 0xfd, 0x90, 0xac, 0xf9, 0x4f, 0xc9, 0x68, 0x0f, 0xba, 0xf6, 0x3d, 0x98, 0x84,
	0xbe, 0x83, 0xce, 0x82, 0x6d, 0xd8, 0x7f, 0xbe, 0x59, 0x19, 0x59, 0x99, 0x31, 0x7a, 0x05, 0x17,
	0xb7, 0x22, 0xdf, 0xad, 0x9e, 0x5a, 0x82, 0x12, 0xe8, 0x1d, 0x88, 0x46, 0xfc, 0x02, 0xda, 0x37,
	0x3c, 0xdf, 0xc9, 0xe3, 0xca, 0x97, 0xd0, 0x31, 0x2c, 0x73, 0x8c, 0x43, 0x70, 0x57, 0x0a, 0xd0,
	0x34, 0x37, 0xc2, 0x81, 0x7e, 0x00, 0x12, 0xb1, 0xdd, 0x72, 0xcb, 0x6e, 0x95, 0xca, 0x5a, 0x12,
	0x38, 0x4d, 0x05, 0xdf, 0x1a, 0x47, 0xfd, 0xac, 0xb6, 0x92, 0xdc, 0x6e, 0x25, 0x39, 0x1d, 0xc1,
	0xa0, 0xa2, 0x34, 0xe9, 0x06, 0xd0, 0xff, 0xb6, 0xce, 0xa4, 0x06, 0x33, 0xe3, 0x47, 0xdf, 0x00,
	0x29, 0x83, 0x26, 0xd1, 0x18, 0x3c, 0x9d, 0x15, 0x4b, 0xd8, 0x8a, 0xcc, 0x44, 0xa7, 0xd0, 0x5b,
	0x08, 0xbe, 0xaf, 0x24, 0xfa, 0xfb, 0x92, 0x03, 0xe8, 0x97, 0x98, 0x68, 0x7b, 0xf5, 0xbb, 0x09,
	0x8d, 0x45, 0x4c, 0xe6, 0xe0, 0x61, 0x91, 0x48, 0x3f, 0x4c, 0xe2, 0xb0, 0x52, 0xde, 0x80, 0x94,
	0x21, 0x93, 0xfc, 0x84, 0xbc, 0x86, 0x53, 0xf5, 0x37, 0x21, 0x17, 0xea, 0xd7, 0xd2, 0x3f, 0x3b,
	0xe8, 0x1d, 0x80, 0x82, 0x3c, 0x07, 0x0f, 0xeb, 0x81, 0xfe, 0x95, 0x4a, 0xa2, 0x7f, 0xad, 0x3d,
	0x5a, 0x82, 0x45, 0x40, 0x49, 0xa5, 0x4b, 0x28, 0xa9, 0xf5, 0xe4, 0x84, 0xbc, 0x87, 0x67, 0xb6,
	0x00, 0x64, 0xa0, 0x18, 0xb5, 0xde, 0x04, 0xc3, 0x2a, 0x58, 0x08, 0x43, 0x70, 0xf5, 0xfd, 0x13,
	0x9d, 0xbd, 0x5c, 0x98, 0xa0, 0x5f, 0x42, 0x0a, 0xfe, 0x17, 0xf5, 0x2d, 0x2b, 0xae, 0x93, 0x8c,
	0x71, 0xe3, 0x7a, 0x33, 0x82, 0xcb, 0x47, 0x78, 0xe1, 0xf0, 0x19, 0xe0, 0x70, 0xc9, 0x64, 0xa4,
	0x88, 0x8f, 0x9a, 0x10, 0x8c, 0xeb, 0x70, 0x21, 0xff, 0x08, 0xad, 0xe2, 0x2e, 0x89, 0xde, 0xaa,
	0x5e, 0x82, 0x60, 0x54, 0x43, 0xad, 0xf6, 0xba, 0xfd, 0x13, 0x42, 0xfc, 0x48, 0x7f, 0x4a, 0xe2,
	0xd8, 0xd3, 0x4f, 0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xa7, 0x0d, 0x5e, 0xd2, 0x05,
	0x00, 0x00,
}
